name: Java CI

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '37 4 * * *'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - uses: gradle/wrapper-validation-action@v1
    - name: gradle cache 
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: NVD cache 
      uses: actions/cache@v1
      with:
        path: ~/.gradle/dependency-check-data
        key: ${{ runner.os }}-nvd-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-nvd-
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew  --info --stacktrace
